apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
      - name: webapp
        image: us-central1-docker.pkg.dev/qwiklabs-gcp-03-82952c0cd3e9/test-repository/webapp
        ports:
        - containerPort: 8080
