steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/webapp', '.']
    dir: 'webapp'

  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['run', 'deploy', 'webapp', '--image', 'gcr.io/$PROJECT_ID/webapp', '--platform', 'managed']

images:
  - 'gcr.io/$PROJECT_ID/webapp'
