steps:
  # Building a Docker image for the web UI application
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/qwiklabs-gcp-03-82952c0cd3e9/test-repository/webapp', './webapp']
    
  # Pushing the Docker image to the Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/qwiklabs-gcp-03-82952c0cd3e9/test-repository/webapp']
    id: 'Push WebApp Image to Test Registry'

  # Obtaining credentials for GKE
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['container', 'clusters', 'get-credentials', 'test-cluster', '--region', 'us-central1', '--project', '$PROJECT_ID']

  # Deploying the application in GKE
  - name: 'google/cloud-sdk'
    entrypoint: 'bash'
    args:
    - '-c'
    - |
      kubectl apply -f app-deployment.yaml
    id: 'Deploy to GKE'
  # Deploying the service in GKE
  - name: 'google/cloud-sdk'
    entrypoint: 'bash'
    args:
    - '-c'
    - |
      kubectl apply -f app-service.yaml
    id: 'Deploy App Service'
